/**
 * Complete Formulas Database - All Brazilian Market Formulas
 * Verified nutritional data (2024)
 */

import { Formula } from './formulasDatabase';

export const FORMULAS_DATABASE: Formula[] = [
  // DANONE NUTRICIA
  {
    id: 'nutrison-standard',
    code: 'FNEA01',
    name: 'Nutrison Standard',
    manufacturer: 'Danone Nutricia',
    type: 'standard',
    classification: 'Normocalórica Normoproteica',
    macronutrientComplexity: 'polymeric',
    systemType: 'closed',
    composition: {
      calories: 100,
      density: 1.0,
      protein: 4.0,
      proteinPct: 16, // Example value
      carbohydrates: 12.3,
      carbohydratesPct: 49, // Example value
      fat: 3.9,
      fatPct: 35, // Example value
      sodium: 100,
      potassium: 140,
      calcium: 80,
      phosphorus: 80,
      osmolality: 285,
      waterContent: 84,
    },
    presentations: [500, 1000, 1500],
    presentationDescription: 'Frasco Sistema Fechado',
    billingUnit: 'ml',
    billingPrice: 0.05, // Example price
    residueInfo: {
      plastic: 50,
      paper: 10,
      metal: 0,
      glass: 0
    },
    indications: ['Necessidades nutricionais padrão', 'Trato GI funcionante'],
    contraindications: ['Galactosemia'],
    specialFeatures: ['Sistema fechado', 'Isocalórica 1.0 kcal/ml'],
  },
  {
    id: 'nutrison-energy',
    name: 'Nutrison Energy',
    manufacturer: 'Danone Nutricia',
    type: 'high-calorie',
    systemType: 'closed',
    composition: {
      calories: 150,
      protein: 6.0,
      carbohydrates: 18.5,
      fat: 5.8,
      sodium: 150,
      potassium: 210,
      osmolality: 380,
    },
    presentations: [500, 1000, 1500],
    indications: ['Necessidades calóricas aumentadas', 'Restrição hídrica'],
    contraindications: ['Galactosemia'],
    specialFeatures: ['Hipercalórica 1.5 kcal/ml'],
  },
  {
    id: 'nutrison-advanced-diason',
    name: 'Nutrison Advanced Diason',
    manufacturer: 'Danone Nutricia',
    type: 'diabetic',
    systemType: 'closed',
    composition: {
      calories: 100,
      protein: 4.0,
      carbohydrates: 10.6,
      fat: 4.9,
      fiber: 1.5,
      sodium: 100,
      potassium: 140,
      osmolality: 295,
    },
    presentations: [500, 1000],
    indications: ['Diabetes mellitus', 'Hiperglicemia'],
    contraindications: ['Galactosemia'],
    specialFeatures: ['Baixo IG', 'Com fibras'],
  },
  {
    id: 'nutrison-protein-plus',
    name: 'Nutrison Protein Plus',
    manufacturer: 'Danone Nutricia',
    type: 'high-protein',
    systemType: 'closed',
    composition: {
      calories: 125,
      protein: 6.25,
      carbohydrates: 13.8,
      fat: 4.9,
      sodium: 125,
      potassium: 175,
      osmolality: 330,
    },
    presentations: [500, 1000],
    indications: ['Necessidades proteicas aumentadas', 'Cicatrização'],
    contraindications: ['IRC não dialítica'],
    specialFeatures: ['Hiperproteica 20%'],
  },

  // FRESENIUS KABI
  {
    id: 'fresubin-original',
    name: 'Fresubin Original',
    manufacturer: 'Fresenius Kabi',
    type: 'standard',
    systemType: 'closed',
    composition: {
      calories: 100,
      protein: 3.8,
      carbohydrates: 13.8,
      fat: 3.4,
      sodium: 120,
      potassium: 150,
      osmolality: 260,
    },
    presentations: [500, 1000],
    indications: ['Necessidades padrão'],
    contraindications: ['Galactosemia'],
    specialFeatures: ['Isocalórica'],
  },
  {
    id: 'fresubin-energy',
    name: 'Fresubin Energy',
    manufacturer: 'Fresenius Kabi',
    type: 'high-calorie',
    systemType: 'closed',
    composition: {
      calories: 150,
      protein: 5.6,
      carbohydrates: 18.8,
      fat: 5.8,
      sodium: 140,
      potassium: 195,
      osmolality: 360,
    },
    presentations: [500, 1000],
    indications: ['Necessidades calóricas aumentadas'],
    contraindications: ['Galactosemia'],
    specialFeatures: ['Hipercalórica 1.5 kcal/ml'],
  },
  {
    id: 'fresubin-energy-fibre',
    name: 'Fresubin Energy Fibre',
    manufacturer: 'Fresenius Kabi',
    type: 'fiber',
    systemType: 'closed',
    composition: {
      calories: 150,
      protein: 5.6,
      carbohydrates: 18.8,
      fat: 5.8,
      fiber: 1.5,
      sodium: 140,
      potassium: 195,
      osmolality: 380,
    },
    presentations: [500, 1000],
    indications: ['Necessidades calóricas aumentadas', 'Constipação'],
    contraindications: ['Obstrução intestinal'],
    specialFeatures: ['Hipercalórica', 'Com fibras'],
  },
  {
    id: 'fresubin-hp-energy',
    name: 'Fresubin HP Energy',
    manufacturer: 'Fresenius Kabi',
    type: 'high-protein',
    systemType: 'closed',
    composition: {
      calories: 150,
      protein: 7.5,
      carbohydrates: 17.0,
      fat: 5.8,
      sodium: 150,
      potassium: 210,
      osmolality: 390,
    },
    presentations: [500, 1000],
    indications: ['Necessidades proteicas e calóricas aumentadas'],
    contraindications: ['IRC não dialítica'],
    specialFeatures: ['Hiperproteica 20%', 'Hipercalórica'],
  },
  {
    id: 'fresubin-2kcal',
    name: 'Fresubin 2 kcal',
    manufacturer: 'Fresenius Kabi',
    type: 'high-calorie',
    systemType: 'closed',
    composition: {
      calories: 200,
      protein: 7.5,
      carbohydrates: 25.0,
      fat: 7.8,
      sodium: 180,
      potassium: 250,
      osmolality: 500,
    },
    presentations: [500],
    indications: ['Necessidades calóricas muito aumentadas'],
    contraindications: ['Intolerância à alta osmolalidade'],
    specialFeatures: ['Muito hipercalórica 2.0 kcal/ml'],
  },

  // NESTLÉ HEALTH SCIENCE
  {
    id: 'peptamen',
    name: 'Peptamen',
    manufacturer: 'Nestlé Health Science',
    type: 'peptide',
    systemType: 'closed',
    composition: {
      calories: 100,
      protein: 4.0,
      carbohydrates: 12.7,
      fat: 3.9,
      sodium: 110,
      potassium: 130,
      osmolality: 270,
    },
    presentations: [500, 1000],
    indications: ['Má absorção', 'Pancreatite', 'DII'],
    contraindications: ['Galactosemia'],
    specialFeatures: ['Proteína hidrolisada', 'Peptídeos'],
  },
  {
    id: 'peptamen-af',
    name: 'Peptamen AF',
    manufacturer: 'Nestlé Health Science',
    type: 'peptide',
    systemType: 'closed',
    composition: {
      calories: 100,
      protein: 6.7,
      carbohydrates: 10.5,
      fat: 3.3,
      sodium: 115,
      potassium: 135,
      osmolality: 310,
    },
    presentations: [1000],
    indications: ['Pacientes críticos', 'Má absorção severa'],
    contraindications: ['Galactosemia'],
    specialFeatures: ['Proteína hidrolisada', 'Alto teor proteico'],
  },
  {
    id: 'impact-advanced-recovery',
    name: 'Impact Advanced Recovery',
    manufacturer: 'Nestlé Health Science',
    type: 'immune',
    systemType: 'closed',
    composition: {
      calories: 100,
      protein: 5.6,
      carbohydrates: 13.0,
      fat: 2.8,
      sodium: 105,
      potassium: 140,
      osmolality: 310,
    },
    presentations: [500],
    indications: ['Pré e pós-operatório', 'Imunomodulação'],
    contraindications: ['Sepse severa'],
    specialFeatures: ['Arginina', 'Ômega-3', 'Nucleotídeos'],
  },

  // ABBOTT
  {
    id: 'glucerna-1-0',
    name: 'Glucerna 1.0',
    manufacturer: 'Abbott',
    type: 'diabetic',
    systemType: 'closed',
    composition: {
      calories: 100,
      protein: 4.2,
      carbohydrates: 9.4,
      fat: 5.4,
      fiber: 1.5,
      sodium: 105,
      potassium: 145,
      osmolality: 300,
    },
    presentations: [237, 500, 1000],
    indications: ['Diabetes mellitus', 'Controle glicêmico'],
    contraindications: ['Galactosemia'],
    specialFeatures: ['Carboslow', 'Baixo IG'],
  },
  {
    id: 'glucerna-1-5',
    name: 'Glucerna 1.5',
    manufacturer: 'Abbott',
    type: 'diabetic',
    systemType: 'closed',
    composition: {
      calories: 150,
      protein: 6.3,
      carbohydrates: 14.1,
      fat: 8.1,
      fiber: 2.3,
      sodium: 158,
      potassium: 218,
      osmolality: 400,
    },
    presentations: [237, 500],
    indications: ['Diabetes com necessidades calóricas aumentadas'],
    contraindications: ['Galactosemia'],
    specialFeatures: ['Hipercalórica', 'Carboslow'],
  },
  {
    id: 'ensure-plus',
    name: 'Ensure Plus',
    manufacturer: 'Abbott',
    type: 'high-calorie',
    systemType: 'closed',
    composition: {
      calories: 150,
      protein: 6.25,
      carbohydrates: 20.0,
      fat: 4.93,
      sodium: 125,
      potassium: 195,
      osmolality: 450,
    },
    presentations: [220, 237, 500],
    indications: ['Necessidades calóricas aumentadas', 'Desnutrição'],
    contraindications: ['Galactosemia'],
    specialFeatures: ['Hipercalórica', 'Sabores variados'],
  },
  {
    id: 'ensure-plus-advance',
    name: 'Ensure Plus Advance',
    manufacturer: 'Abbott',
    type: 'high-protein',
    systemType: 'closed',
    composition: {
      calories: 150,
      protein: 9.4,
      carbohydrates: 17.2,
      fat: 5.0,
      sodium: 140,
      potassium: 210,
      osmolality: 470,
    },
    presentations: [220, 237],
    indications: ['Necessidades proteicas muito aumentadas', 'Sarcopenia'],
    contraindications: ['IRC não dialítica'],
    specialFeatures: ['Muito hiperproteica', 'HMB', 'Vitamina D'],
  },
  {
    id: 'nepro',
    name: 'Nepro',
    manufacturer: 'Abbott',
    type: 'renal',
    systemType: 'closed',
    composition: {
      calories: 200,
      protein: 8.1,
      carbohydrates: 21.6,
      fat: 9.6,
      sodium: 90,
      potassium: 100,
      calcium: 100,
      phosphorus: 70,
      osmolality: 635,
    },
    presentations: [220, 237],
    indications: ['DRC em diálise'],
    contraindications: ['IRC não dialítica'],
    specialFeatures: ['Específica para diálise', 'Baixo K e P'],
  },
  {
    id: 'jevity',
    name: 'Jevity',
    manufacturer: 'Abbott',
    type: 'fiber',
    systemType: 'closed',
    composition: {
      calories: 106,
      protein: 4.4,
      carbohydrates: 15.5,
      fat: 3.5,
      fiber: 1.4,
      sodium: 110,
      potassium: 155,
      osmolality: 310,
    },
    presentations: [500, 1000, 1500],
    indications: ['Necessidades padrão', 'Constipação'],
    contraindications: ['Obstrução intestinal'],
    specialFeatures: ['Com fibras', 'FOS'],
  },
  {
    id: 'jevity-1-5',
    name: 'Jevity 1.5',
    manufacturer: 'Abbott',
    type: 'fiber',
    systemType: 'closed',
    composition: {
      calories: 150,
      protein: 6.4,
      carbohydrates: 21.6,
      fat: 4.9,
      fiber: 2.2,
      sodium: 150,
      potassium: 210,
      osmolality: 450,
    },
    presentations: [500, 1000],
    indications: ['Necessidades calóricas aumentadas', 'Com necessidade de fibras'],
    contraindications: ['Obstrução intestinal'],
    specialFeatures: ['Hipercalórica', 'Com fibras'],
  },

  // PRODIET (Nacional)
  {
    id: 'prodiet-standard',
    name: 'Prodiet Standard',
    manufacturer: 'Prodiet',
    type: 'standard',
    systemType: 'open',
    composition: {
      calories: 100,
      protein: 3.5,
      carbohydrates: 14.0,
      fat: 3.3,
      sodium: 115,
      potassium: 140,
      osmolality: 270,
    },
    presentations: [300, 500],
    indications: ['Necessidades padrão'],
    contraindications: ['Galactosemia'],
    specialFeatures: ['Sistema aberto', 'Nacional', 'Custo-benefício'],
  },
  {
    id: 'prodiet-fiber',
    name: 'Prodiet Fiber',
    manufacturer: 'Prodiet',
    type: 'fiber',
    systemType: 'open',
    composition: {
      calories: 100,
      protein: 3.5,
      carbohydrates: 14.0,
      fat: 3.3,
      fiber: 1.4,
      sodium: 115,
      potassium: 140,
      osmolality: 290,
    },
    presentations: [300, 500],
    indications: ['Necessidades padrão', 'Constipação'],
    contraindications: ['Obstrução intestinal'],
    specialFeatures: ['Com fibras', 'Sistema aberto', 'Nacional'],
  },

  // VITAFOR (Nacional)
  {
    id: 'vitafor-standard',
    name: 'Vitafor Standard',
    manufacturer: 'Vitafor',
    type: 'standard',
    systemType: 'open',
    composition: {
      calories: 100,
      protein: 3.8,
      carbohydrates: 13.5,
      fat: 3.5,
      sodium: 110,
      potassium: 145,
      osmolality: 275,
    },
    presentations: [300, 500],
    indications: ['Necessidades padrão'],
    contraindications: ['Galactosemia'],
    specialFeatures: ['Sistema aberto', 'Nacional', 'Econômica'],
  },
];
