// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { defineConfig } from "prisma/config";

const hasValue = (value: string | undefined): value is string => typeof value === "string" && value.trim().length > 0;

const configDir = path.dirname(fileURLToPath(import.meta.url));
const candidatePaths = [
  path.resolve(process.cwd(), ".env"),
  path.resolve(process.cwd(), "server", ".env"),
  path.resolve(configDir, ".env"),
];

for (const envPath of candidatePaths) {
  if (!fs.existsSync(envPath)) continue;
  const fileContent = fs.readFileSync(envPath, "utf8");
  for (const line of fileContent.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const separatorIndex = trimmed.indexOf("=");
    if (separatorIndex === -1) continue;

    const key = trimmed.slice(0, separatorIndex).trim();
    const rawValue = trimmed.slice(separatorIndex + 1).trim();
    const normalizedValue = rawValue.replace(/^(['"])(.*)\1$/, "$2");

    if (!hasValue(process.env[key])) {
      process.env[key] = normalizedValue;
    }
  }
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
